# TinyWorld configuration
 
ui:
  deps:
    logging:      # logging for dependencies
      wwj: on     # on/off
      flatlaf: on # on/off
 
indexor:
  # Default TinyWorld's embedded cluster is running at localhost:9200
  # Make sure to edit config below if there's another OpenSearch / Elasticsearch cluster running at this address or if you don't want to use the embedded one.
  cluster:
    embedded:
      enabled: true     # true to use TinyWorld's embedded cluster, false to use external OpenSearch / Elasticsearch cluster
      expose: false     # true to expose cluster to external machines (with CORS enabled as well). Default to false.
    address: localhost  # address of OpenSearch / Elasticsearch cluster
    port: 9200          # cluster listening port
 